### ISSUE TITLE
Connection problem with 1.2.12

### ISSUE THREAD

**Issue by mirkanglanz** [BrainAppeal/t3monitor#10]
TYPO3 10.4.32 LTS, Server-Software Apache,
PHP Version 7.4.33, MySQL 5.7.35

After the update it does not connect, opening the link /?eID=t3monitor&secret=a______c&reports=security,installed_extensions,sys_log,system,install_tool,database&last_check=1669172792 shows the following error message: 

OutOfBoundsExceptionprototypeobject
   message => protected'Cannot seek to 0 which is behind offset 0 plus count 0' (54 chars)
   code => protected0 (integer)
   file => protected'/html/public/typo3conf/ext/t3monitor/Classes/Reports/SysLog.php' (72 chars)
   line => protected109 (integer)

Works fine with 1.2.11.

**Comment by bahammes** [comment]
Since 1.2.12 the t3monitor extension reads the last 50 lines from the TYPO3 system log file (var/log/typo3_xyz.log), to track errors in the log file.

There was a check missing, if the file exists, but is completely empty.
This bug is fixed in the new release  [1.2.13](https://github.com/BrainAppeal/t3monitor/releases/tag/1.2.13)

The log entries are displayed in the status report section:

![T3Monitor_system_log](https://user-images.githubusercontent.com/7912777/203793552-b55f73f2-ecf8-4db0-a3c0-ada0a866c439.png)
