### ISSUE TITLE
connection problem with 1.2.9

### ISSUE THREAD

**Issue by mirkanglanz** [BrainAppeal/t3monitor#5]
I can't establish a connection 

When I open the connection-check: 
/?eID=t3monitor&secret=XXXXX&reports=security,installed_extensions,sys_log,system,applications,install_tool,database
The following error is shown: Unable to generate a URL for the named route "tools_toolssettings" because this route was not found.

TYPO3 10.4.27, composer based.

Downgrading to 1.2.7 fixes it for me.

**Comment by bahammes** [comment]
Thank you for reporting the issue.

The bug is fixed in the new release 1.2.10.

Reason for the bug:
When running the security checks for the install tool password in \TYPO3\CMS\Install\Report\SecurityStatusReport and the default install tool password is still used, the report creates a link to the install tool settings action.
The route "tools_toolssettings" is only available in the backend context and therefore not available in the t3monitor extension.

**Comment by mirkanglanz** [comment]
Alright. Thank you!
